### ISSUE TITLE
torch.OutOfMemoryError: Allocation on device

### ISSUE THREAD

**Issue by ddddddeyrueuad** [huanngzh/ComfyUI-MVAdapter#2]
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "C:\comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MVAdapter\nodes.py", line 410, in sample
    images = pipeline(
             ^^^^^^^^^
  File "C:\comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MVAdapter\mvadapter\pipelines\pipeline_mvadapter_i2mv_sdxl.py", line 653, in __call__
    "ref_hidden_states": {k: v.clone() for k, v in ref_hidden_states.items()},
                             ^^^^^^^^^
torch.OutOfMemoryError: Allocation on device

**Comment by huanngzh** [comment]
We recommend running MV-Adapter on the GPU with 24GB, due to the large base model SDXL.

**Comment by tiandaoyuxi** [comment]
![image](https://github.com/user-attachments/assets/7b97c6ae-6289-4c62-9ff2-ca2f5421022a)
Same problem…

**Comment by huanngzh** [comment]
Can you provide some specific settings (e.g. `height`, `width` in ImageProcessor and Diffusers MV Sampler nodes) and screenshots of the workflow? Or, is it the default workflow that is used directly?

**Comment by coddz** [comment]
run ok when I reduce the width and height to 512*512.

**Comment by huanngzh** [comment]
Hi, I added a new option `upcast_fp32` to the LDM VAE Loader node. It is recommended to use the VAE from [sdxl-vae-fp16-fix](https://huggingface.co/madebyollin/sdxl-vae-fp16-fix) and set the option `upcast_fp32` to `False`. I tested it on Ubuntu system with 4090 GPU and it works.

If you still get errors, feel free to let us know and we will fix it further.

**Comment by ddddddeyrueuad** [comment]
How can use local sdxl model？now,I only use online load sdxl base model(from Huggingface),can not use local model.



---Original---
From: "Zehuan ***@***.***&gt;
Date: Fri, Dec 6, 2024 22:03 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [huanngzh/ComfyUI-MVAdapter] torch.OutOfMemoryError: Allocationon device (Issue #2)




 
Hi, I added a new option upcast_fp32 to the LDM VAE Loader node. It is recommended to use the VAE from sdxl-vae-fp16-fix and set the option upcast_fp32 to False. I tested it on Ubuntu system with 4090 GPU and it works.
 
If you still get errors, feel free to let us know and we will fix it further.

**Comment by huanngzh** [comment]
> How can use local sdxl model？now,I only use online load sdxl base model(from Huggingface),can not use local model.
> […](#)
> ---Original--- From: "Zehuan ***@***.***&gt; Date: Fri, Dec 6, 2024 22:03 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [huanngzh/ComfyUI-MVAdapter] torch.OutOfMemoryError: Allocationon device (Issue #2) Hi, I added a new option upcast_fp32 to the LDM VAE Loader node. It is recommended to use the VAE from sdxl-vae-fp16-fix and set the option upcast_fp32 to False. I tested it on Ubuntu system with 4090 GPU and it works. If you still get errors, feel free to let us know and we will fix it further. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Do you mean the local ldm-format model?

**Comment by ddddddeyrueuad** [comment]
Mo idm



---Original---
From: "Zehuan ***@***.***&gt;
Date: Sun, Dec 8, 2024 13:25 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [huanngzh/ComfyUI-MVAdapter] torch.OutOfMemoryError: Allocationon device (Issue #2)




  
How can use local sdxl model？now,I only use online load sdxl base model(from Huggingface),can not use local model.
 …
 ---Original--- From: "Zehuan @.&gt; Date: Fri, Dec 6, 2024 22:03 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [huanngzh/ComfyUI-MVAdapter] torch.OutOfMemoryError: Allocationon device (Issue #2) Hi, I added a new option upcast_fp32 to the LDM VAE Loader node. It is recommended to use the VAE from sdxl-vae-fp16-fix and set the option upcast_fp32 to False. I tested it on Ubuntu system with 4090 GPU and it works. If you still get errors, feel free to let us know and we will fix it further. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Do you mean the local ldm-format model?

**Comment by 1blackbar** [comment]
wowz so 3090 is low VRAM now ? cmon guys, prune the weights
