### ISSUE TITLE
爆显存了。

### ISSUE THREAD

**Issue by ddddddeyrueuad** [huanngzh/ComfyUI-MVAdapter#35]
原来使用3060 12G显卡可以跑，但是升级后直接BOOM显存。是不是出了什么问题？（加了显存清除也不行）

**Comment by huanngzh** [comment]
I have just updated some code but not sure whether it matters. Could you help try it again?

**Comment by mumpischlumpi** [comment]
I have the same problem on a 4090 with 24GB Vram. Before the update I only had occasional OOM errors. Now I can no longer use the workflow.

**Comment by huanngzh** [comment]
@mumpischlumpi Does it mean that all workflows don't work, or dont work only after adding the view selector? Does it also not work with my latest updated code? Could you provide more detailed information?

**Comment by mumpischlumpi** [comment]
I am sorry, that seems to have been a false alarm. I have freshly reinstalled ComfyUI and now it works again without memory errors. 

However, I had the problem that the node does not install correctly at first (Import Failed) and I have to upgrade huggingface hub with “python_embeded\python.exe -m pip install --upgrade huggingface_hub” to make it work.

**Comment by ddddddeyrueuad** [comment]
> 我在 4090 的 24GB VRAM 上遇到了同样的问题。在更新之前，我只是偶尔出现 OOM 错误。现在我不能再使用工作流了。

3090和4090更新与否，都正常工作。没遇到问题啊。

**Comment by ddddddeyrueuad** [comment]
> 我刚刚更新了一些代码，但不确定它是否重要。您能帮忙再试一次吗？

I was test.result is weight and height set 512*512 is ok,but 768*768 is boom yet,before update is not this wrong

**Comment by ddddddeyrueuad** [comment]
> > 我刚刚更新了一些代码，但不确定它是否重要。您能帮忙再试一次吗？
> 
> 我被测了一下，结果是体重和身高设定512_512还行，但是768_768还行，更新前还没这个错

i was updated this node

**Comment by serI0usLIn** [comment]
> 原来使用3060 12G显卡可以跑，但是升级后直接BOOM显存。是不是出了什么问题？（加了显存清除也不行）

@ddddddeyrueuad 有没有推荐的大模型，我手上的能出图但是都是噪点

**Comment by ddddddeyrueuad** [comment]
不会啊，我的就是3060，项目上说了，是用sdxl. Base模型



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年3月17日(周一) 中午1:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [huanngzh/ComfyUI-MVAdapter] 爆显存了。 (Issue #35)


    
原来使用3060 12G显卡可以跑，但是升级后直接BOOM显存。是不是出了什么问题？（加了显存清除也不行）
  
@ddddddeyrueuad 有没有推荐的大模型，我手上的能出图但是都是噪点

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
  serI0usLIn left a comment (huanngzh/ComfyUI-MVAdapter#35)
  
原来使用3060 12G显卡可以跑，但是升级后直接BOOM显存。是不是出了什么问题？（加了显存清除也不行）
  
@ddddddeyrueuad 有没有推荐的大模型，我手上的能出图但是都是噪点
